// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-xNRmzLS3eB9SNnfLwm5BE1SVwj1P-Fg',
    appId: '1:1076321850553:android:ed9fed8ee702c74c3e3768',
    messagingSenderId: '1076321850553',
    projectId: 'test-cloud-storage-6ae34',
    storageBucket: 'test-cloud-storage-6ae34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgut1hU0ZFnUgSrcWDvSkAax7k1itFuJY',
    appId: '1:1076321850553:ios:6dc2a05b5ce9d5e63e3768',
    messagingSenderId: '1076321850553',
    projectId: 'test-cloud-storage-6ae34',
    storageBucket: 'test-cloud-storage-6ae34.appspot.com',
    iosClientId: '1076321850553-p1h799obahrrjfst4ac7ujpn8bv6mgkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.testCloudStorage',
  );
}
